import { Metadata } from 'next';
import React from 'react';
import { fonts } from './font';

import '@/styles/global.scss';

type Props = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by create next app',
  icons: [
    { rel: 'apple-touch-icon', url: '/favicon/apple-touch-icon.png' },
    { rel: 'icon', url: '/favicon/favicon.ico' },
  ],
  manifest: '/favicon/site.webmanifest',
};

export default function RootLayout(props: Props) {
  const { children } = props;

  return (
    <html>
      <body className={fonts.roboto.className}>{children}</body>
    </html>
  );
}
